# Generated by Django 3.2.17 on 2023-02-17 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Email_ID',
            new_name='email_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Employee_id',
            new_name='employee_id',
        ),
    ]
