# Generated by Django 3.2.17 on 2023-02-27 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230226_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='current_user',
        ),
        migrations.AddField(
            model_name='device',
            name='current_user',
            field=models.ManyToManyField(to='api.Employee'),
        ),
        migrations.AlterField(
            model_name='history',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device'),
        ),
    ]
