# Generated by Django 3.2.17 on 2023-02-27 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20230227_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='model',
        ),
    ]
