# Generated by Django 3.2.17 on 2023-03-01 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20230228_0621'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='device',
            name='current_user',
        ),
        migrations.DeleteModel(
            name='HistoricalDevice',
        ),
        migrations.DeleteModel(
            name='HistoricalEmployee',
        ),
        migrations.AddField(
            model_name='history',
            name='dev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device'),
        ),
        migrations.AddField(
            model_name='history',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
        ),
        migrations.AddField(
            model_name='device',
            name='current_user',
            field=models.ManyToManyField(through='api.History', to='api.Employee'),
        ),
    ]
