# Generated by Django 3.2.17 on 2023-03-02 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20230301_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='emp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
        ),
        migrations.CreateModel(
            name='History2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('dev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device')),
                ('emp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
    ]
