# Generated by Django 3.2.17 on 2023-03-02 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20230302_1809'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='History2',
            new_name='Status',
        ),
    ]
