# Generated by Django 3.2.17 on 2023-03-02 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_history2_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='status',
            unique_together={('dev', 'emp')},
        ),
    ]
