# Generated by Django 3.2.17 on 2023-03-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_status_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='status',
            unique_together=set(),
        ),
    ]
